import Link from 'next/link'
import { getAllPosts, Post } from 'libs/posts'
import { GetStaticProps } from 'next'

export interface BlogPageProps {
  posts: Post[]
}
export default function BlogPage({ posts }: BlogPageProps) {
  return (
    <div className="wrapper">
      <h1>All Posts</h1>
      <p>
        Click the link below to navigate to a page generated by <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post, index) => (
          <li key={index}>
            <Link href={`posts/${post.slug}`}>{post.title}</Link>
          </li>
        ))}
      </ul>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = getAllPosts()

  return {
    props: { posts },
  }
}
